#=============For Font Change=========================

!jt -t grade3 -tf firacode -tfs 13 -mathfs 110 -fs 13 -N -T

#========================For Theme Change===============================

!jt -t oceans16

# Numpy Arrays
linear algebra  libraary, important for data science. all the libraries in the pydata ecosystem rely on Numpy,

In [31]:
#library imports for numpy array

import numpy as np
from numpy import array
from numpy import empty

In [22]:
l=[1.0,2.0,3.0,4.0]   #========== 'l'  is the list here
a=array(l)          #===============this converts the array list 'l' inton the array 'a'

print(a)   #============prints the arrray 'a'

[1. 2. 3. 4.]


In [26]:
#======= Arrays have an inbuilt method namenl 'shape()' that determines the shape of the given array
print(a.shape)  #============OR
a.shape

(4,)


(4,)

In [27]:
emp=np.empty([3,3])
print(emp)

[[6.90574425e-310 6.90574425e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.30276956e+180]
 [1.57076922e-076 4.57399529e-071 3.25746024e-086]]


In [29]:
#==========To create an array with all the elements '0' in it==========
#========== The argument in the brackets indicate the dimensions of the array

a1=np.zeros([3,5])
print(a1)

a1.shape  # =============Shape of the created array==========

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(3, 5)

In [32]:
# =================To Create an array with all elements equall to one use "ones()" an inbuilt function
a2=np.ones([3,5])
print(a2)

a2.shape  #===========the shape of the created array==============

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


(3, 5)

In [33]:
#============Vstack is an inbuilt fuction that stacks one array to other vertically on it=================
a3=np.vstack((a1,a2))
print(a3)

In [38]:
#========hstack is an inbuilt function that stack two arrys horizontially===========
x1=[1,2,3,4]
x2=[5,6,7,8]
a4=np.hstack((x1,x2))
print(a4)

# array slicing

In [49]:
lis = [[1,2,3], [4,5,6], [7,8,9]]
print(lis)

print("=======================================================")
slic = np.array(lis)
print(slic)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
#=======this slice will print from 2nd row onwards with all colomuns==============
print(slic[1:])

[[4 5 6]
 [7 8 9]]


In [53]:
twod=array([[10,20,30],[40,50,60],[70,80,90]])

In [54]:
print(twod)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [55]:
td=twod[:, :-1]
#===========this will slice the last column but print rest of the columns and all the rows
print(td)

[[10 20]
 [40 50]
 [70 80]]


In [58]:
tc=twod[:,-1] 
#===============this will print only the last column and rest of the columns and all the rows will be sliced
print(tc)

[30 60 90]


In [79]:
data=np.array([11,22,33,44,55,66])

In [80]:
data

array([11, 22, 33, 44, 55, 66])

In [81]:
data.shape

(6,)

In [82]:
#========To change the shape of the arrray, numpy has an inbuilt method called as "reshape()"
#========this changes the shape of the array according to to the given arguments
data.reshape(3,2)
#=========The above code will  change the array into 2D array of Shape with three rows and two columns

array([[11, 22],
       [33, 44],
       [55, 66]])

In [61]:
data=data.reshape((data.shape[0],1))

In [10]:
data

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [91]:
data.shape

(6, 1)

In [100]:
a=np.array([1,2,3])
b=2

In [103]:
c=a+b

#===========This adds the integer value to the array  by element wise to all elements in it

In [104]:
c

array([3, 4, 5])

In [25]:

arry=[2,4,6,8,10]
def findNumber(arr):
    
    
    global arry
    #print(len(arry))
    
    n = int(input("Enter the number to search in the array : "))
    for i in arr:
        if n in arr:
            print("Element {} found..! ".format(n,i))
            break
        else:
            print("Element {} not found!".format(n))
            break
    arry.append(n)
findNumber(arry)

Enter the number to search in the array : 3
Element 3 not found!


In [26]:
arry

[2, 4, 6, 8, 10, 3]

In [21]:
def oddNumbers(l, r):
    # Write your code hereor 
    for i in range(l,r):
        if(i%2!=0):
            print(i)
oddNumbers(2,9)

3
5
7


In [34]:
Max = np.array(arry)

In [37]:
print("Maximum element of array is : ", Max.max())
print("Minimum  element of the array id : ",Max.min())

Maximum element of array is :  10
Minimum  element of the array id :  2


In [39]:
print("The index of the maximum element of the array is ...........",Max.argmax())
print("The index minimum element of the the array is ..............", Max.argmin())

The index of the maximum element of the array is ........... 4
The index minimum element of the the array is .............. 0


In [53]:
#======The arrays differ from list by broadcasting i-e in lists there is no concept of broadcasting============
print("In this Broadcasting the change will be reflected in the orginal array.")

list = [1,2,3,4,5,6,7,8,9]

ARRAY = np.array(list)
print("Array Before Broadcasting.........: ",ARRAY)
print("\n")
print("=================================================================")
ARRAY[0:5] = 500
print("\n")
print("Array after Braodcasting...... : ",ARRAY)



In this Broadcasting the change will be reflected in the orginal array.
Array Before Broadcasting.........:  [1 2 3 4 5 6 7 8 9]




Array after Braodcasting...... :  [500 500 500 500 500   6   7   8   9]


In [59]:
print("In this type of Bradcasting the change will not be reflected in the orginal array.")

Array_copy = ARRAY.copy()
Array_copy[:] = 100
print(Array_copy)

#====== here the change will not be reflected in the orginal array===========

In this type of Bradcasting the change will not be reflected in the orginal array.
[100 100 100 100 100 100 100 100 100]


In [60]:
ARRAY

array([500, 500, 500, 500, 500, 500, 500, 500, 500])

In [62]:
ARRAY[:2] = 12
ARRAY[2:3] = 23
ARRAY[3:4] = 35
ARRAY[4:6] = 10
ARRAY[7:9] = 50

print(ARRAY)

[ 12  12  23  35  10  10 500  50  50]


# Numpy operations

In [66]:
ADDED_ARRAY = ARRAY + ARRAY   #=========== addition of two  numpy arrays =============

print("Array after Addition .................. : ", ADDED_ARRAY)
print("\n")

SUB_ARRAY = ARRAY - ARRAY     #============Subtraction of Two Arrays==================
print("Array fater Subtraction............... :",SUB_ARRAY)
print("\n")

POW_ARRAY = ARRAY ** 2     #===========Square of an Array========================
print("The square of the array is ................ : ", ARRAY)

Array after Addition .................. :  [  24   24   46   70   20   20 1000  100  100]


Array fater Subtraction............... : [0 0 0 0 0 0 0 0 0]


The square of the array is ................ :  [ 12  12  23  35  10  10 500  50  50]


In [67]:
ARRAY_100 = ARRAY + 100 #============Element wise addition of 100=================
print("array after the addition of 100............: ",ARRAY_100)

array after the addition of 100............:  [112 112 123 135 110 110 600 150 150]


# Universal fuctions in Numpy

In [74]:
print("Array after squareroot......: ",np.sqrt(ARRAY))
print("\n")
print("Array after Exponential......: ",(np.exp(ARRAY)))
print("\n")
print("Array maximum element of array....: ",np.max(ARRAY))
print("\n")
print("Array after log......: ",(np.log(ARRAY)))
print("\n")
print("Array after sin operation......: ",np.sin(ARRAY))
print("\n")


Array after squareroot......:  [ 3.46410162  3.46410162  4.79583152  5.91607978  3.16227766  3.16227766
 22.36067977  7.07106781  7.07106781]


Array after Exponential......:  [1.62754791e+005 1.62754791e+005 9.74480345e+009 1.58601345e+015
 2.20264658e+004 2.20264658e+004 1.40359222e+217 5.18470553e+021
 5.18470553e+021]


Array maximum element of array....:  500


Array after log......:  [2.48490665 2.48490665 3.13549422 3.55534806 2.30258509 2.30258509
 6.2146081  3.91202301 3.91202301]


Array after sin operation......:  [-0.53657292 -0.53657292 -0.8462204  -0.42818267 -0.54402111 -0.54402111
 -0.46777181 -0.26237485 -0.26237485]




In [76]:
Log_Space = np.logspace(1,100,20)  #=====logspace() it generates the logrithmic values  between the given numbers 
#                                  #=====in as arguments, here 20 indicates the total no. of numbers 
print(Log_Space)

[1.00000000e+001 1.62377674e+006 2.63665090e+011 4.28133240e+016
 6.95192796e+021 1.12883789e+027 1.83298071e+032 2.97635144e+037
 4.83293024e+042 7.84759970e+047 1.27427499e+053 2.06913808e+058
 3.35981829e+063 5.45559478e+068 8.85866790e+073 1.43844989e+079
 2.33572147e+084 3.79269019e+089 6.15848211e+094 1.00000000e+100]


In [99]:
list = [1,2,3,4,5,6,7,8,9]
arr_2D = np.array(list)
arr_2D.reshape(3,3)
print(np.isnan(arr_2D))

print("the mean of the given array is .....", np.mean(arr_2D))

print("The cumSum for given  array is ............: ", arr_2D.cumsum())
print("The varience of the given array is ......: ", np.var(arr_2D))
print("The Squeeze of given array is.......: ", arr_2D.squeeze)

A = arr_2D.flatten()

B = arr_2D.ravel()

print(A)

print(B)



[False False False False False False False False False]
the mean of the given array is ..... 5.0
The cumSum for given  array is ............:  [ 1  3  6 10 15 21 28 36 45]
The varience of the given array is ......:  6.666666666666667
The Squeeze of given array is.......:  <built-in method squeeze of numpy.ndarray object at 0x7f25082f4f30>
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [103]:
print(np.tile(A,2))
print(np.tile(B,2))



print(np.repeat(A,2))

print(np.repeat(B,2))

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]
[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]


In [107]:
print(np.random.seed(1))  #======Seed function is used to save the state of random function, so that it can generate
#======some random numbers on multiple execution of the code on the same machine or on different machines 

unique = np.unique(arr_2D)

None


In [108]:
index = np.where(arr_2D > 5) #---------returns the indexes where the values are greate than 5

print(index)

(array([5, 6, 7, 8]),)
